import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MainMenu } from "@/shared/components/main-menu";
import { Suspense, unstable_ViewTransition as ViewTransition } from "react";
import { SessionWrapper } from "@/lib/session.provider";
import { authOptions } from "@/lib/auth";
import { getServerSession } from "next-auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <SessionWrapper>
          <header>
            <MainMenu session={session} />
          </header>

          <main className="mt-[var(--header-height)]">
            <ViewTransition name="auto">{children}</ViewTransition>
          </main>
        </SessionWrapper>
      </body>
    </html>
  );
}
